### ISSUE TITLE
NUGet Package

### ISSUE THREAD

**Issue by jeanie77** [Bernardo-Castilho/CalcEngine#14]
Hello, thanks a lot for your library!
I would like to reference it as a NUGet Package but, looking at NUGet Gallery, I've only found this package: [https://www.nuget.org/packages/CalcEngine.Core](https://www.nuget.org/packages/CalcEngine.Core)
It is a porting for .NET of your [CodeProject article](https://www.codeproject.com/Articles/246374/A-Calculation-Engine-for-NET), but  I'm still using .NET Framework.
Can I help in some way, maybe creating the package and publishing it on the gallery? It's a new task for me, but I'll try to make it.
Please let me know.

**Comment by Bernardo-Castilho** [comment]
Hello!

Glad you found the library useful.

I have no plans to create any nuget packages for it, so feel free to do it.

Best of luck and thanks for letting me know!
________________________________
From: jeanie77 ***@***.***>
Sent: Tuesday, February 6, 2024 12:10 PM
To: Bernardo-Castilho/CalcEngine ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bernardo-Castilho/CalcEngine] NUGet Package (Issue #14)


Hello, thanks a lot for your library!
I would like to reference it as a NUGet Package but, looking at NUGet Gallery, I've only found this package: https://www.nuget.org/packages/CalcEngine.Core
It is a porting for .NET of your CodeProject article<https://www.codeproject.com/Articles/246374/A-Calculation-Engine-for-NET>, but I'm still using .NET Framework.
Can I help in some way, maybe creating the package and publishing it on the gallery? It's a new task for me, but I'll try to make it.
Please let me know.

**Comment by jeanie77** [comment]
Hello! I wrote you an email last week, to decide how to proceed. Did you receive it?

**Comment by Bernardo-Castilho** [comment]
Hello!

Yes, I did receive your e-mail, but didn't have time to work on it.

I will do that later this week, OK?

Thank you for your patience...
________________________________

**Comment by Bernardo-Castilho** [comment]
Hi Jeanie

1) Title of the package.
The package is called CalculationEngine at the moment, but it’s temporary. Since "CalcEngine" is already taken, I would like to add a prefix, like "Net.CalcEngine" or "Castilho.CalcEngine", If you would like to appear in the name.

_** I prefer "Net.CalcEngine" (or maybe "CalcEngine.Net"?)_

2) License.
Ok with MIT License, as already chosen for github project?

_** I am OK with MIT, no problem._

3) Package Info.
We mentioned you in the information because you are the author of the project. If it’s okay with you, I would go with these info:
Title: (see above)
Authors: Bernardo Castilho
Description: A Calculation Engine for .NET

_** Sounds good!_

4) Readme.
In readme section I would like to mention your github repository and probably you should, in turn, mention this nuget package in your readme, if we want them to be linked.

_** I'll be happy to mention the nuget package in the readme. Just tell me when it's available and I will update the readme._

5) Pull request.
All the above informations are written in CalcEngine.csproj file. To make them permanent, we could push them to your repository. Do you agree to make this change to the repository?

_** Sure, go ahead with the edits you need and submit a pull request so I can review and accept it._

Thanks!

**Comment by jeanie77** [comment]
Hi Bernardo, we finally succeeded in integrating your library with NuGet, thanks for your support and collaboration!

**Comment by Bernardo-Castilho** [comment]
Great, it was a pleasure working with you on this!
